<a href="https://colab.research.google.com/github/lianghuizi/DeepLearning/blob/main/%E5%88%9D%E5%A7%8B%E5%85%89%E7%85%A7%E5%9B%BE%E4%BC%B0%E8%AE%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 假想的暗光图像 L （5x5x3）
L=np.array([
    [[30, 25, 20], [40, 35, 30], [50, 45, 40], [45, 40, 35], [35, 30, 25]],
    [[35, 30, 25], [45, 40, 35], [55, 50, 45], [50, 45, 40], [40, 35, 30]],
    [[40, 35, 30], [50, 45, 40], [60, 55, 50], [55, 50, 45], [45, 40, 35]],
    [[35, 30, 25], [45, 40, 35], [55, 50, 45], [50, 45, 40], [40, 35, 30]],
    [[30, 25, 20], [40, 35, 30], [50, 45, 40], [45, 40, 35], [35, 30, 25]]
])

In [ ]:
# TODO:实现初始光照图估计 T_hat= max(R,G,B)
T_hat=np.max(L,axis=2)
print(f'shape:{T_hat.shape}')
print(T_hat)

shape:(5, 5)
[[30 40 50 45 35]
 [35 45 55 50 40]
 [40 50 60 55 45]
 [35 45 55 50 40]
 [30 40 50 45 35]]
